config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Footer
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path   %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("logo_transparent_back_cropped.png", alt: "rh logo"), 
                                              root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav" id="headernav">
        <li><%= link_to "About",  about_path%></li>
        <li><%= link_to "Home",   root_path %></li>
        <li id="fat-menu" class="dropdown">
          <a href='#' class="dropdown-toggle" data-toggle="dropdown">
            Rates <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", '#'  %></li>
            <li><%= link_to "Settings", '#' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", '#'%>
            </li>
          </ul>
        </li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ROCKHAUS | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 
                        'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>    
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About page</h1>
<p>
  <%= link_to 'go to home page', 'home' %>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="center jumbotron">
  <h1>RockHaus contact page</h1>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>help page</h1>
<p>
  <%= link_to "go to homepage", "home" %>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>RockHaus home page</h1>
  <p>
    <a href="http://www.rockhausgym.com/">Current RockHaus website</a>
  </p>
</div>